### PR TITLE
62 docker evnironment for buildroot

### LINKED ISSUE #62: [Compilation] - Dockerize buildroot runs
### Description

Currently linux is required to build odysseus.  Many people do not have linux, and others have to spend the hassle of getting the right packages installed.  Even then, there are random issues that keep popping up. 

### Acceptance Criteria

- quick docker run command 
- volumes for all outputs and a way to notify that they should be persisted
- out-of-tree by default to ease development
- binding to external tree so host machine can make changes live
- readme instructions which describe the build and run command and other commands such as pruning and updated
- descriptions about how to fetch the sd card image from the environment to  be flashed, and how to do things like scp out
- ascii art (most important imo)

### Proposed Solution

Making a docker container to run buildroot will have a small performance penalty, but will be worth it for wider accessibility and ease of environment setup.  Furthermore it can prevent host system errors leading to fixes that are one off for personal computers.

### PR DESCRIPTION
**Pull request by jr1221**
## Changes

Adds a docker build system to buildroot.  Uses docker compose.

## Notes

Most info regarding its layout is in the README under the docker heading.

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please reach out to your Project Lead if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [ ] All commits are tagged with the ticket number
- [X] No merge conflicts
- [n/a] All checks passing
- [X] Remove any non-applicable sections of this template
- [X] Assign the PR to yourself
- [X] Request reviewers & ping on Slack
- [X] PR is linked to the ticket (fill in the closes line below)

Closes #62 

I have no idea why a bunch of old commits are showing up.

### CODE REVIEW

**Comment by nwdepatie** [comment]
A way we can speed up the docker build process is to build it and push it to dockerhub, and then have the docker compose just pull that container so we don't have to wait for it to build. Not too important but potential optimization

**Comment by nwdepatie** [comment]
Should probably modify the README to reflect the change in setup (this really streamlined setup my god) to be just docker build, cd into directory, then make

**Comment by nwdepatie** [comment]
I think you can definitely streamline to a single command by running something along the lines of `docker exec make -j$(nproc+1) --output=target` with the respective commands. That should prob be done before this PR is merged in with the README updated

**Review by nwdepatie — CHANGES_REQUESTED** [review]
This is really really nice quality of life PR and has a lot of potential to expand or CI CD and dev experience. I think we gotta kinda stress test (very loosely used lol) this a bit to account for "what if I leave the docker container then rebuild" etc.

Also I think before we merge this in we should get it down to a single or two docker commands rather than having to enter into the shell of the container itself which I think is possible

**Comment by jr1221** [comment]
> I think you can definitely streamline to a single command by running something along the lines of `docker exec make -j$(nproc+1) --output=target` with the respective commands. That should prob be done before this PR is merged in with the README updated

Do you mean after the container is already running? Like run the container detached to background, then use a one-liner docker exec to build?

I was thinking this:
```
docker compose run --rm --build odysseus -d
(container id returned here)
docker exec <container_id> -w /home/odysseus/outputs/<ap|tpu|nero>/ make -j`nproc` --output-sync=target
```

**Comment by nwdepatie** [comment]
Also note for me that I was able to successfully build in the container on my machine

**Pull request merged**
