### PR TITLE
Split nero and TPU systems

### LINKED ISSUE #39: Split NERO and TPU Defconfigs
Right now NERO 2.0 is set to be built into the TPU. While this might become true later down the line, we want them to be separate for the time being until we make the call to consolidate. This will speed up boot times, optimize resources, and speed up build times for each platform for now

### PR DESCRIPTION
**Pull request by jr1221**
## Changes

Nero and tpu refactored with:
- seperate  defconfigs
- seperate overlays (different network types in seperate PR)
- a unified `nrc_common` overlay for all defconfigs that use HaLow
- adds readme info for this defconfig and how to build it out of tree

Also:
- corrrected fsck utilities that were lost in a previous PR
- fixes a spelling mistake with ap defconfig hostname

## Notes

There are leftover commits from a previous PR here I have no idea why.  However the diff is correct.  A follow-up PR will add the nero AP and cleanup the nero networking configurations.

Since I got write perms for confluence after I made this PR when I start looking into #41 I will reduce the size of the README in favor of the confluence page.

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please reach out to your Project Lead if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [ ] All commits are tagged with the ticket number (oops I had no idea i had to do this)
- [X] No merge conflicts
- [n/a] All checks passing
- [X] Remove any non-applicable sections of this template
- [X] Assign the PR to yourself
- [X] Request reviewers & ping on Slack
- [X] PR is linked to the ticket (fill in the closes line below)

Closes #39

### CODE REVIEW

**Comment by nwdepatie** [comment]
So NERO built, might be a local system thing but I got these warnings when compiling the QT part:
```
CMake Warning (dev) at /home/nwdepatie/Siren/odysseus/buildroot/output/per-package/nero2/host/aarch64-buildroot-linux-gnu/sysroot/usr/lib/cmake/Qt6Core/Qt6CoreMacros.cmake:2702 (message):
  Qt policy QTP0001 is not set: ':/qt/qml/' is the default resource prefix
  for QML modules.  Check https://doc.qt.io/qt-6/qt-cmake-policy-qtp0001.html
  for policy details.  Use the qt_policy command to set the policy and
  suppress this warning.

Call Stack (most recent call first):
  /home/nwdepatie/Siren/odysseus/buildroot/output/per-package/nero2/host/aarch64-buildroot-linux-gnu/sysroot/usr/lib/cmake/Qt6Qml/Qt6QmlMacros.cmake:445 (__qt_internal_setup_policy)
  _deps/ds-src/src/imports/components/CMakeLists.txt:2 (qt6_add_qml_module)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at /home/nwdepatie/Siren/odysseus/buildroot/output/per-package/nero2/host/aarch64-buildroot-linux-gnu/sysroot/usr/lib/cmake/Qt6Core/Qt6CoreMacros.cmake:2702 (message):
  Qt policy QTP0001 is not set: ':/qt/qml/' is the default resource prefix
  for QML modules.  Check https://doc.qt.io/qt-6/qt-cmake-policy-qtp0001.html
  for policy details.  Use the qt_policy command to set the policy and
  suppress this warning.

Call Stack (most recent call first):
  /home/nwdepatie/Siren/odysseus/buildroot/output/per-package/nero2/host/aarch64-buildroot-linux-gnu/sysroot/usr/lib/cmake/Qt6Qml/Qt6QmlMacros.cmake:445 (__qt_internal_setup_policy)
  _deps/ds-src/src/imports/effects_qt6/CMakeLists.txt:2 (qt6_add_qml_module)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at /home/nwdepatie/Siren/odysseus/buildroot/output/per-package/nero2/host/aarch64-buildroot-linux-gnu/sysroot/usr/lib/cmake/Qt6Core/Qt6CoreMacros.cmake:2702 (message):
  Qt policy QTP0001 is not set: ':/qt/qml/' is the default resource prefix
  for QML modules.  Check https://doc.qt.io/qt-6/qt-cmake-policy-qtp0001.html
  for policy details.  Use the qt_policy command to set the policy and
  suppress this warning.

Call Stack (most recent call first):
  /home/nwdepatie/Siren/odysseus/buildroot/output/per-package/nero2/host/aarch64-buildroot-linux-gnu/sysroot/usr/lib/cmake/Qt6Qml/Qt6QmlMacros.cmake:445 (__qt_internal_setup_policy)
  _deps/ds-src/src/imports/flowview/CMakeLists.txt:6 (qt6_add_qml_module)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at /home/nwdepatie/Siren/odysseus/buildroot/output/per-package/nero2/host/aarch64-buildroot-linux-gnu/sysroot/usr/lib/cmake/Qt6Core/Qt6CoreMacros.cmake:2702 (message):
  Qt policy QTP0001 is not set: ':/qt/qml/' is the default resource prefix
  for QML modules.  Check https://doc.qt.io/qt-6/qt-cmake-policy-qtp0001.html
  for policy details.  Use the qt_policy command to set the policy and
  suppress this warning.

Call Stack (most recent call first):
  /home/nwdepatie/Siren/odysseus/buildroot/output/per-package/nero2/host/aarch64-buildroot-linux-gnu/sysroot/usr/lib/cmake/Qt6Qml/Qt6QmlMacros.cmake:445 (__qt_internal_setup_policy)
  _deps/ds-src/src/imports/logichelper/CMakeLists.txt:2 (qt6_add_qml_module)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at /home/nwdepatie/Siren/odysseus/buildroot/output/per-package/nero2/host/aarch64-buildroot-linux-gnu/sysroot/usr/lib/cmake/Qt6Core/Qt6CoreMacros.cmake:2702 (message):
  Qt policy QTP0001 is not set: ':/qt/qml/' is the default resource prefix
  for QML modules.  Check https://doc.qt.io/qt-6/qt-cmake-policy-qtp0001.html
  for policy details.  Use the qt_policy command to set the policy and
  suppress this warning.

Call Stack (most recent call first):
  /home/nwdepatie/Siren/odysseus/buildroot/output/per-package/nero2/host/aarch64-buildroot-linux-gnu/sysroot/usr/lib/cmake/Qt6Qml/Qt6QmlMacros.cmake:445 (__qt_internal_setup_policy)
  _deps/ds-src/src/imports/multitext/CMakeLists.txt:2 (qt6_add_qml_module)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at /home/nwdepatie/Siren/odysseus/buildroot/output/per-package/nero2/host/aarch64-buildroot-linux-gnu/sysroot/usr/lib/cmake/Qt6Core/Qt6CoreMacros.cmake:2702 (message):
  Qt policy QTP0001 is not set: ':/qt/qml/' is the default resource prefix
  for QML modules.  Check https://doc.qt.io/qt-6/qt-cmake-policy-qtp0001.html
  for policy details.  Use the qt_policy command to set the policy and
  suppress this warning.

Call Stack (most recent call first):
  /home/nwdepatie/Siren/odysseus/buildroot/output/per-package/nero2/host/aarch64-buildroot-linux-gnu/sysroot/usr/lib/cmake/Qt6Qml/Qt6QmlMacros.cmake:445 (__qt_internal_setup_policy)
  _deps/ds-src/src/imports/tools/eventsimulator/CMakeLists.txt:6 (qt6_add_qml_module)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at /home/nwdepatie/Siren/odysseus/buildroot/output/per-package/nero2/host/aarch64-buildroot-linux-gnu/sysroot/usr/lib/cmake/Qt6Core/Qt6CoreMacros.cmake:2702 (message):
  Qt policy QTP0001 is not set: ':/qt/qml/' is the default resource prefix
  for QML modules.  Check https://doc.qt.io/qt-6/qt-cmake-policy-qtp0001.html
  for policy details.  Use the qt_policy command to set the policy and
  suppress this warning.

Call Stack (most recent call first):
  /home/nwdepatie/Siren/odysseus/buildroot/output/per-package/nero2/host/aarch64-buildroot-linux-gnu/sysroot/usr/lib/cmake/Qt6Qml/Qt6QmlMacros.cmake:445 (__qt_internal_setup_policy)
  _deps/ds-src/src/imports/tools/eventsystem/CMakeLists.txt:7 (qt6_add_qml_module)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at /home/nwdepatie/Siren/odysseus/buildroot/output/per-package/nero2/host/aarch64-buildroot-linux-gnu/sysroot/usr/lib/cmake/Qt6Core/Qt6CoreMacros.cmake:2702 (message):
  Qt policy QTP0001 is not set: ':/qt/qml/' is the default resource prefix
  for QML modules.  Check https://doc.qt.io/qt-6/qt-cmake-policy-qtp0001.html
  for policy details.  Use the qt_policy command to set the policy and
  suppress this warning.

Call Stack (most recent call first):
  /home/nwdepatie/Siren/odysseus/buildroot/output/per-package/nero2/host/aarch64-buildroot-linux-gnu/sysroot/usr/lib/cmake/Qt6Qml/Qt6QmlMacros.cmake:445 (__qt_internal_setup_policy)
  _deps/ds-src/src/imports/application/CMakeLists.txt:6 (qt6_add_qml_module)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at /home/nwdepatie/Siren/odysseus/buildroot/output/per-package/nero2/host/aarch64-buildroot-linux-gnu/sysroot/usr/lib/cmake/Qt6Core/Qt6CoreMacros.cmake:2702 (message):
  Qt policy QTP0001 is not set: ':/qt/qml/' is the default resource prefix
  for QML modules.  Check https://doc.qt.io/qt-6/qt-cmake-policy-qtp0001.html
  for policy details.  Use the qt_policy command to set the policy and
  suppress this warning.

Call Stack (most recent call first):
  /home/nwdepatie/Siren/odysseus/buildroot/output/per-package/nero2/host/aarch64-buildroot-linux-gnu/sysroot/usr/lib/cmake/Qt6Qml/Qt6QmlMacros.cmake:445 (__qt_internal_setup_policy)
  qmlmodules:4 (qt6_add_qml_module)
  CMakeLists.txt:63 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at /home/nwdepatie/Siren/odysseus/buildroot/output/per-package/nero2/host/aarch64-buildroot-linux-gnu/sysroot/usr/lib/cmake/Qt6Core/Qt6CoreMacros.cmake:2702 (message):
  Qt policy QTP0001 is not set: ':/qt/qml/' is the default resource prefix
  for QML modules.  Check https://doc.qt.io/qt-6/qt-cmake-policy-qtp0001.html
  for policy details.  Use the qt_policy command to set the policy and
  suppress this warning.

Call Stack (most recent call first):
  /home/nwdepatie/Siren/odysseus/buildroot/output/per-package/nero2/host/aarch64-buildroot-linux-gnu/sysroot/usr/lib/cmake/Qt6Qml/Qt6QmlMacros.cmake:445 (__qt_internal_setup_policy)
  content/CMakeLists.txt:5 (qt6_add_qml_module)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at /home/nwdepatie/Siren/odysseus/buildroot/output/per-package/nero2/host/aarch64-buildroot-linux-gnu/sysroot/usr/lib/cmake/Qt6Core/Qt6CoreMacros.cmake:2702 (message):
  Qt policy QTP0001 is not set: ':/qt/qml/' is the default resource prefix
  for QML modules.  Check https://doc.qt.io/qt-6/qt-cmake-policy-qtp0001.html
  for policy details.  Use the qt_policy command to set the policy and
  suppress this warning.

Call Stack (most recent call first):
  /home/nwdepatie/Siren/odysseus/buildroot/output/per-package/nero2/host/aarch64-buildroot-linux-gnu/sysroot/usr/lib/cmake/Qt6Qml/Qt6QmlMacros.cmake:445 (__qt_internal_setup_policy)
  imports/NERO/CMakeLists.txt:10 (qt6_add_qml_module)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    BUILD_DOC
    BUILD_DOCS
    BUILD_EXAMPLE
    BUILD_EXAMPLES
    BUILD_TEST
    BUILD_TESTING
    BUILD_TESTS
    CMAKE_COLOR_MAKEFILE

```

**Comment by jr1221** [comment]
That is something nero does not specify in its cmake configuration.  I believe it's just tue equivalent of leaving a path to the qml files blank so it's warning it's choosing the default path.  I got the error too on my end and nero still worked correctly.  I can raise the issue with Peyton, but I doubt it's a problem?

**Comment by nwdepatie** [comment]
Looks like all three built, I think you're good to go to merge

**Review by nwdepatie — APPROVED** [review]
builds yippee

**Pull request merged**
